#!/usr/bin/env bash
# https://github.com/nicknisi/dotfiles/blob/master/install/brew.sh

if test ! "$( command -v brew )"; then
    echo "Installing homebrew"
    ruby -e "$( curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install )"
fi

echo -e "\\n\\nInstalling homebrew packages..."
echo "=============================="

formulas=(
    pass
    tig
#   dnsmasq
#   git
#   bash
)

for formula in "${formulas[@]}"; do
    if brew list "$formula" > /dev/null 2>&1; then
        echo "$formula already installed... skipping."
    else
        brew install "$formula"
    fi
done

if  java --version > /dev/null 2>&1; then
    echo "java already installed... skipping."
else
    brew cask install java
fi