# Source commonrc
source $HOME/.commonrc

# Source helper files
[ -d $HOME/bash.d ] && \
    for file in "$(find -L $HOME/bash.d -maxdepth 1 -type f)"; do source $file; done

# Source bash completion files 
[ -d /usr/local/etc/bash_completion.d ] && \
    for file in "$(find -L /usr/local/etc/bash_completion.d -maxdepth 1 -type f)"; do source $file; done